### ISSUE TITLE
Error with LoggerAwareInterface

### ISSUE THREAD

**Issue by UksusoFF** [sirn-se/websocket-php#15]
`setLogger` must return `void`: https://github.com/php-fig/log/blob/master/src/LoggerAwareInterface.php#L17
In your lib it returns `self`. It's produce error with `declare(strict_types=1);` and PHP 8.1+

```
  Declaration of WebSocket\Client::setLogger(Psr\Log\LoggerInterface $logger): WebSocket\Client must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void
```

**Comment by sirn-se** [comment]
Yes, `v2.0.1` removes support for `psr/log v3` to circumvent this issue.

Method profile will be changed next major release (it is a breaking change).
