### ISSUE TITLE
PHP fatal error in connection

### ISSUE THREAD

**Issue by cprobst87** [sirn-se/websocket-php#17]
**Describe the bug**
Some days I got this fatal error in connection.php

My script is like this:
```
$client = new WebSocket\Client("wss://websocket-api.tibber.com/v1-beta/gql/subscriptions");
$client ->addHeader("Sec-WebSocket-Protocol", "graphql-transport-ws")
    // Add CloseHandler middleware
    ->addMiddleware(new WebSocket\Middleware\CloseHandler())
    // Add PingResponder middleware
    ->addMiddleware(new WebSocket\Middleware\PingResponder()); 

$client->text($connectionTibber);  

$timestop = intval(date("Hi"));
while ($timestop < 2130) {
	$timestop = intval(date("Hi"));
    $tdauer = microtime(true) - $tstart;
    
    try { 
        file_put_contents("last_".$datei, Zeitstempel()." - --- NEUE RUNDE, nächster Befehl ist receive()! Letzte Message: $TibberMessage --- \n", FILE_APPEND | LOCK_EX);   
        $TibberMessage = $client->receive();
[...]some more code[...]
}
catch (\WebSocket\ConnectionException $e) {
        // Possibly log errors
			print_r(Zeitstempel()." - Error: ".$e->getMessage()."\n");
			errlog($mysqli);
		}    
}
$client->text('{"id": "Verbrauchsmessung","type": "stop"}');
$client->close();
```

**How to reproduce**
I don't know. I think the server has a problem? Or my internet connection?

**Logs**
```
PHP Fatal error:  Uncaught WebSocket\Exception\ConnectionClosedException: Connection has unexpectedly closed in /volume1/web/verbrauch/vendor/phrity/websocket/src/Connection.php:342
Stack trace:
#0 /volume1/web/verbrauch/vendor/phrity/websocket/src/Connection.php(273): WebSocket\Connection-&gt;throwException(Object(RuntimeException))
#1 /volume1/web/verbrauch/vendor/phrity/websocket/src/Client.php(249): WebSocket\Connection-&gt;pullMessage()
#2 /volume1/web/verbrauch/calcEinspeisung.php(31): WebSocket\Client-&gt;receive()
#3 {main}
  thrown in /volume1/web/verbrauch/vendor/phrity/websocket/src/Connection.php on line 342
```

**Versions**
* Version of this library newest
* PHP version 8

**Comment by sirn-se** [comment]
There might be several reasons why the connection fails. There could be an error, but also that the server automatically closes sockets that haven't been in use for some time. A websocket implementation _should_ expect and handle that a connection gets closed.

You do attempt to catch such errors in your code, but you're catching the wrong exception. That's why you get a fatal error. In `2.0` the exceptions are more specific, you should catch the `WebSocket\Exception\ConnectionClosedException` or possibly the `WebSocket\Exception\ConnectionLevelInterface` which is shared by all connection level exceptions.

You might also want to have a look at the [subscription flow](https://github.com/sirn-se/websocket-php/blob/v2.0-main/docs/Client.md#subscribe-operation) which is more efficient when subscribing to server messages.

**Comment by cprobst87** [comment]
Thank you!
So i added:
```
catch (\WebSocket\ConnectionException | \WebSocket\Exception\ConnectionClosedException | \WebSocket\Exception\ConnectionLevelInterface $e) {
        // Possibly log errors
			print_r(Zeitstempel()." - Error ConnectionException, try to reconnect: ".$e->getMessage()."\n");
			errlog($mysqli);
            echo "Exception! Try to reconnect!\n\n";
            $client->close();
            $client->connect();
            $client->text($connectionTibber);  
		}    
```   

Could that work? With close and connect?
I will try the [subscription flow](https://github.com/sirn-se/websocket-php/blob/v2.0-main/docs/Client.md#subscribe-operation) as well in a few days

**Comment by sirn-se** [comment]
- You only need to listen to `\WebSocket\Exception\ConnectionClosedException` **or** `\WebSocket\Exception\ConnectionLevelInterface`, not both. And not the old exception that no longer will be thrown.
- You can skip the `close()` and `connect()` calls, the client will automatically re-connect (if required) when sending or receiving messages.

**Comment by cprobst87** [comment]
Hi again,
sorry for my stupid questions, I think that will be better in the discussions so we can close that here, with receive() and the correct Exeptions it works! 
Now I'm just trying the other solution... [Discussion](https://github.com/sirn-se/websocket-php/discussions/18)
