### ISSUE TITLE
How to decode recieved message?

### ISSUE THREAD

**Issue by UksusoFF** [sirn-se/websocket-php#19]
After connect `$message->getContent()` returns:
```
"0{\"sid\":\"FfmKOWoZI7KTh8lUAAgZ\",\"upgrades\":[],\"pingInterval\":25000,\"pingTimeout\":5000}"
```
Next messages also started from number. E.g.:
```
"42[\"message\",\"{\\\"id\\\":\\\"f9345251-6ec5-44cd-9db8-cd03956773a4\\\",\\\"action\\\":\\\"update\\\",\\\"entity\\\...
```
Any way to get payload without this numbers?

**Comment by sirn-se** [comment]
The `getContent()` returns the content payload, which is always a string. Any encoding/decoding expected by service has to be handled by the implementation using it. So you need to check the documentation of the service you're connecting to.
