### ISSUE TITLE
Public client connection

### ISSUE THREAD

**Issue by alexevladgabriel** [sirn-se/websocket-php#2]
**Is it within the scope of this library?**
I would like that the connect method to be available, to be able to use isConnected on checking the status of connection when sending text/commands to the websocket.

**Describe the solution you'd like**
Change protected in Client:306 to public or static.

**Comment by sirn-se** [comment]
Version `1.7.0` just released, where the `connect()` methods are changed to public.

It will still auto-connect if send/received called without having manually connected first.

Closing.
