### ISSUE TITLE
http upgrade to websocket support?

### ISSUE THREAD

**Issue by kocoten1992** [sirn-se/websocket-php#23]
Hi, thanks for the library!

I'm trying to connect to a websocket to a https url (and then it will get upgrade to websocket), but I'm facing this error:

```
WebSocket\Exception\BadUriException  Invalid URI scheme, must be 'ws' or 'wss'.
```

It seem WebSocket/Client is not supported that (or there is a way), thank you very much!

**Comment by sirn-se** [comment]
The upgrade handshake is part of websocket protocol, so you need to use `wss://` schema. If the server support websockets it should allow it.

**Comment by kocoten1992** [comment]
It work now, thank you very much!
