### ISSUE TITLE
PSR-compatible issue

### ISSUE THREAD

**Issue by bbuugg** [sirn-se/websocket-php#27]
**Describe the bug**
Please provide a clear and concise description of the suspected issue.

```
Declaration of WebSocket\Connection::setLogger(Psr\Log\LoggerInterface $logger): WebSocket\Connection must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void
```

The affected file is "Client.php", "Connection.php", "MiddlewareHandler.php" and so on...

**Versions**

i am using "laravel/framework": "^10.28", the psr/http-message version is 2.0, my php version is 8.2

**Comment by sirn-se** [comment]
`psr/log v3` compability is scheduled for the next major version of this repo, see [v3.0 announcement](https://github.com/sirn-se/websocket-php/discussions/25).

`laravel/framework` requires `psr/log: ^1.0|^2.0|^3.0` so it is not incompatible by itself.
