### ISSUE TITLE
On the issue of version

### ISSUE THREAD

**Issue by amiaozz** [sirn-se/websocket-php#37]
First of all, allow me to explain that my English is very poor. I beg your pardon because the content is machine translation.
My PHP version is 7.4.So the project library I can use is 1.7.2.Is there any invisible problem? Because I noticed the lack of some document example functions such as getContent(), my business scenario is to create a ws client.Thank you very much.I'm sorry if I disturbed you.I'm worried about having BUG in the production environment.

**Comment by sirn-se** [comment]
You can find the documentation for `v1.7` here: [Client](https://github.com/sirn-se/websocket-php/blob/1.7.2/docs/Client.md), [Message](https://github.com/sirn-se/websocket-php/blob/1.7.2/docs/Message.md).

**Comment by amiaozz** [comment]
Okay, thank you very much.
