### ISSUE TITLE
Psr log v3

### ISSUE THREAD

**Issue by simPod** [sirn-se/websocket-php#49]
Hello, is there any plan for psr/log v3 support?

**Comment by sirn-se** [comment]
Yes, it will be included in `v3` as it is a breaking change. 
No time estimation though, there are other some changes that will be breaking I want to incorporate as well.

**Comment by Crease29** [comment]
Heya, I'm using Symfony 7 which requires `psr/log` v3 by default. Does that mean I'm currently not able to use `sirn-se/websocket-php` in that project or is there any workaround which allows me to use it? Thank you!

**Comment by sirn-se** [comment]
Hi @Crease29 

It shouldn't be a problem.

Looking at `symfony/symfony v7` it require `psr/log: ^1|^2|^3`. As long as there is "common ground", Composer is able to resolve dependencies.

**Comment by Crease29** [comment]
For now I solved it by manually adding `"psr/log": "^2"` to my composer.json.
Looking forward to `sirn-se/websocket-php:3`, thank you for your work!

**Comment by sirn-se** [comment]
Version `3.0.0` just released, supporting `psr/log 3.0`. Closing issue.
