### ISSUE TITLE
Support psr/http-message 2.0

### ISSUE THREAD

**Issue by MarcusOhman91** [sirn-se/websocket-php#5]
Any reason it is restricted to version 1?
https://github.com/sirn-se/websocket-php/blob/6b5e04e3df95344dc25c389a38705794b8739626/composer.json#LL29C24-L29C24

Also why was textalk/websocket-php abandoned? There are only mentions in issues that this should be used in favour but no explanation why.

Thanks

**Comment by sirn-se** [comment]
Version `1.7.0` just released, with updated dependencies.
Closing.
