### ISSUE TITLE
version 1.7.2 not compatible with psr/http-message 1.0

### ISSUE THREAD

**Issue by pwolanin** [sirn-se/websocket-php#60]
**Describe the bug**
Please provide a clear and concise description of the suspected issue.

After pulling in the update to dmore/chrome-mink-driver (2.9.2 => 2.9.3) that adopted this library we are getting a fatal error:

```
PHP Fatal error:  Declaration of WebSocket\Http\Message::withProtocolVersion(string $version): WebSocket\Http\Message must be compatible with Psr\Http\Message\MessageInterface::withProtocolVersion($version) in /var/www/drupal/vendor/phrity/websocket/lib/Http/Message.php on line 42
```

https://github.com/sirn-se/websocket-php/compare/1.7.1...1.7.2

The problem is that the parent class does not have the string typing of the parameter.

**How to reproduce**
If possible, provide information - possibly including code snippets - on how to reproduce the issue.

**Logs**
If possible, provide logs that indicate the issue. See https://github.com/Textalk/websocket-php/blob/master/docs/Examples.md#echo-logger on how to use the EchoLog. 

**Versions**
* Version of this library: 1.7.2
* PHP version: PHP 8.2.18

**Comment by sirn-se** [comment]
I'll have a look at this when I have time. You should be able to use version `1.1` of `psr/http-message`.

**Comment by sirn-se** [comment]
`1.7.3` specifies correct dependency version.
