### ISSUE TITLE
PSR interface type (above PSR2)

### ISSUE THREAD

**Issue by julienfollow** [sirn-se/websocket-php#63]
Hi
When i try to start a server on my symfony project with PSR4 (for my case), I have lot of issue with interface. 
Why you don't type your interface ? Because you break the dogme of interface :smiling_face_with_tear: 
![image](https://github.com/sirn-se/websocket-php/assets/70938205/259917f4-d448-416c-9410-69acf6917a97)

Do you have a PR to type interface ? 

Regards

**Comment by sirn-se** [comment]
Hi,

This repo fully support [`PSR-4`](https://www.php-fig.org/psr/psr-4/) autoloading.

The error message indicate that you have `psr/http-message 1.0` installed.
Current version of this repo specifies `psr/http-message  ^1.1 | ^2.0` as requirement.

So please check and update your dependencies to get compatible versions.
