### ISSUE TITLE
>onText callback

### ISSUE THREAD

**Issue by sacOO7** [sirn-se/websocket-php#71]
Is code written inside >onText blocking or nonblocking? 
Does this library make use of php fibres to achieve concurrency ? 
How is this library different from https://github.com/amphp/websocket-client and https://github.com/ratchetphp/Pawl

**Comment by sacOO7** [comment]
If it uses fibers internally, why isn't is build on top of ampPhp and reactPhp instead

**Comment by sirn-se** [comment]
Hi,
No simple answers to your questions but I'll give it a try.

This library uses a custom coroutine setup, similar to Fibers but limited/optimized for actually use. I have considered switching to Fibers but as the functional benefit is pretty low it's not a priority at this point.

The listener callbacks are invoked after a message have been read from stream, so they're not blocking as such - unless you add blocking code in them.

I'm not familiar with mentioned libraries, but maybe someone else can make a comparison.

**Comment by sacOO7** [comment]
Thanks for the answer !
Btw, I was interested in your custom coroutine setup : > Can you point me to the code ?

**Comment by sirn-se** [comment]
The run loop is in the `start()` method of [Server](https://github.com/sirn-se/websocket-php/blob/v3.1-main/src/Server.php#L299) and [Client](https://github.com/sirn-se/websocket-php/blob/v3.1-main/src/Client.php#L257) respectively. 
The "queue" is populated by [`waitRead()`](https://github.com/sirn-se/phrity-net-stream/blob/main-v2/src/StreamCollection.php#L105) that in turn uses `stream_select()`. This way the entire instance share a single wait state, connections will never block each other.

So it's not a generalized coroutine setup (although there is a `onTick(...)` listener that allows adding custom code).
