### ISSUE TITLE
Secure connection

### ISSUE THREAD

**Issue by e-sau** [sirn-se/websocket-php#75]
Hello, @sirn-se 

Help me, please to understand, how to configure websocket server to accept secure connections?

When we create SocketServer (https://github.com/sirn-se/phrity-net-stream/blob/main-v2/src/SocketServer.php#L42) we don't provide a context option and server throw exception - `stream_socket_accept(): SSL_R_NO_SHARED_CIPHER: no suitable shared cipher could be used.  This could be because the server is missing an SSL certificate (local_cert context option)`.

May be, I don't know, something?

**Comment by sirn-se** [comment]
Hi @e-sau 

This issue has as much to do with server configuration as setting up the PHP code. In short, you need to have openssl installed, its certificates must be readable, PHP must have it enabled, and client and server must share at least one cipher to use.

Run `php -i`, you should get a section with `openssl` configurations. Ensure they appear correct and that the files it points to are readable by the user running the server script.

Run `openssl` to review the configuration for OpenSSL.

My test server just runs on default settings, so I haven't really explored this. Maybe someone else have managed to solve this and can give some hints?

Theoretically you should be able to set things up manually in PHP, but I realize now I never added the `setContext()` on Server, only on Client. I will schedule server context support for next version of this repo.

I've also seen solutions where people use `ngingx` as proxy for web sockets, handling SSL in the proxy instead. Not sure why they prefer this solution, maybe nginx has better SSL support than PHP?

**Comment by sirn-se** [comment]
`v3.2` released, support setContext() on Server class. Closing.
