### ISSUE TITLE
Server failed to start: Could not create socket

### ISSUE THREAD

**Issue by jepster** [sirn-se/websocket-php#78]
Hi there!

I am running phrity/websocket:3.2 on MacOS with PHP 8.3.8. I could start the server once and communicate via a client. But now I do get always this error message, when I try to open a connection from the client: 
```
[PHP-FPM    ] [04-Oct-2024 21:23:34 UTC] [critical] Uncaught PHP Exception WebSocket\Exception\ServerException: "Server failed to start: Could not create socket for "tcp://0.0.0.0:8000"." at Server.php line 476
```
I reverted to the state, where it was working and also restarted my machine. In doubt, that any ports or sockets got blocket. Nothing helped. Do you have any idea, what could make my server unable to start?

**Comment by sirn-se** [comment]
Those socket errors are not very specific, so hard to debug. As you had it working (although only shortly) my guess is that the socket is already in use.

It can occur
- If your script is trying to use a previously opened socket that haven't been closed
- If another application is using the same socket
- FPM in error indicates you're running as a web service, if multiple requests attempts to create a server with the same socket they will block each other

Things you could try
- Use another port (if another application is using `8000`}
- Try running the server directly without FPM
- Attach a logger to the server - this will give more specific information of what the server is doing
