### ISSUE TITLE
PHP Fatal error:  Uncaught WebSocket\BadOpcodeException: Invalid opcode '12'

### ISSUE THREAD

**Issue by cprobst87** [sirn-se/websocket-php#8]
Hello,
I wrote a script to interact with the Tibber API to collect my produced kWh.
That works fine for more than one months. I start the script with my NAS and it works every day for 9h.
Yesterday I got an error from the server and the script is terminated. There is a catch block, but it was thrown anyway. Is that ok or a bug?

I use your script like this:

```
include "./vendor/autoload.php";
$client = new WebSocket\Client("wss://websocket-api.tibber.com/v1-beta/gql/subscriptions", [
      'headers' => [
        'Sec-WebSocket-Protocol' => 'graphql-transport-ws'
        ],
			['filter' => ['text', 'binary', 'ping', 'pong', 'close']],
			'timeout' => 60// 1 minute time out
        ]);
$connection = '{"type":"connection_init","payload":{"token":"123"}}';        
$client->text($connection);

$message = "";  
$timestop = intval(date("Hi"));
while ($timestop < 2130) {
	$timestop = intval(date("Hi"));
    try {
        $message = $client->receive();          
\\Some more code here...
 } catch (\WebSocket\ConnectionException $e) {
        // Possibly log errors
			print_r("Error: ".$e->getMessage()."\n");
```

**How to reproduce**
I have no access to the Tibber server ;)

**Logs**
Error: Connection closed: Empty read; connection dead?
Error: Invalid status code 504.
PHP Fatal error:  Uncaught WebSocket\BadOpcodeException: Invalid opcode '12' provided in /volume1/web/verbrauch/vendor/phrity/websocket/lib/Frame/Frame.php:32
Stack trace:
#0 /volume1/web/verbrauch/vendor/phrity/websocket/lib/Frame/FrameHandler.php(93): WebSocket\Frame\Frame-&gt;__construct('12', 'tml&gt;\r\n&lt;head&gt;&lt;ti...', false)
#1 /volume1/web/verbrauch/vendor/phrity/websocket/lib/Message/MessageHandler.php(63): WebSocket\Frame\FrameHandler-&gt;pull()
#2 /volume1/web/verbrauch/vendor/phrity/websocket/lib/Connection.php(207): WebSocket\Message\MessageHandler-&gt;pull()
#3 /volume1/web/verbrauch/vendor/phrity/websocket/lib/Client.php(240): WebSocket\Connection-&gt;pullMessage()
#4 /volume1/web/verbrauch/calcEinspeisung.php(23): WebSocket\Client-&gt;receive()
#5 {main}
  thrown in /volume1/web/verbrauch/vendor/phrity/websocket/lib/Frame/Frame.php on line 32

**Versions**
Version of this library newesd
PHP version 8

**Comment by sirn-se** [comment]
Hi @cprobst87 

The reason for this error is that the service you're connecting to is using a non-standard opcode. The `opcode '12'` you can see in the error text.

WebSocket **do** support extensions that implement additional opcodes, so this is perfectly valid.

However I haven't implemented support for extensions in this repo yet. It is on my todo-list, but a lot of things are at the time so I'm not sure when this will be solved

**Comment by cprobst87** [comment]
Hello,thank you for your answer. That is Ok for me, no problem!Thank you and have a nice day.Chris 

    Am Dienstag, 17. Oktober 2023 um 15:22:28 MESZ hat Sören Jensen ***@***.***> Folgendes geschrieben:  
 
 


Hi @cprobst87

The reason for this error is that the service you're connecting to is using a non-standard opcode. The opcode '2' you can see in the error text.

WebSocket do support extensions that implement additional opcodes, so this is perfectly valid.

However I haven't implemented support for extensions in this repo yet. It is on my todo-list, but a lot of things are at the time so I'm not sure when this will be solved
